version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build: .
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
